### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by derwin-ngomane**
derwin 2018 annotations

### CODE REVIEW

**Comment by lastrucci01** [comment]
Hey @u14309468,

The files look like they are in the interim format. 
The final format should be:
- title
- blank line
- author name OR vukuzenzele unnamed
- blank line
- article text

You can view the completed annotations for 2020-2022 for examples.
I understand the formatting wasn't very clearly communicated and I am really sorry about that, and I will work to make proper instructions to help future annotators.

**Comment by lastrucci01** [comment]
Also, I understand you have put a lot of effort into this already, so let me know if there is anything I can do to make it easier.

**Comment by lastrucci01** [comment]
I made a doc to avoid further confusion [here](https://github.com/dsfsi/vukuzenzele-nlp/blob/master/docs/annotations_instr.md), I would appreciate feedback after having experienced doing the annotations if I missed anything 👍

**Comment by derwin-ngomane** [comment]
@lastrucci01 I have made updates, please check again

**Comment by vukosim** [comment]
@lastrucci01, please check and get back to @derwin-ngomane

**Pull request merged**
