### PR TITLE
Add common story files in all languages

### PR DESCRIPTION
**Pull request by vukosim**
headings and paragraph article provided

### CODE REVIEW

**Comment by vukosim** [comment]
Hey @Daniel-Ind. I created the pull request here. 

Do we know if the stories have the name of the writer? If so, can we also add that name as a new line after the title?

**Comment by vukosim** [comment]
Create folders for each edition amd then put the txt files

interim/2022-07-ed1/

@Daniel-Ind

**Comment by vukosim** [comment]
Think it is best to name the file 2021-07-ed1-vukuzenzele-001-tso.txt for example for the xintsonga one. Think this naming scheme is a bit better @Daniel-Ind

**Comment by Daniel-Ind** [comment]
> Create folders for each edition amd then put the txt files
> 
> interim/2022-07-ed1/
> 
> @Daniel-Ind

- directory has been created and files have been uploaded.

**Review by vukosim — COMMENTED** [review]
LFTM

**Pull request merged**
