### PR TITLE
Add extracted stories

### PR DESCRIPTION
**Pull request by Daniel-Ind**
Manual extraction

### CODE REVIEW

**Review by vukosim — COMMENTED** [review]
@Daniel-Ind Are these automatically extracted only, or they were automatically extracted and then you fixed them?

**Comment by Daniel-Ind** [comment]
@vukosim 
They are automatically extracted then fixed.

**Comment by vukosim** [comment]
Okay. interim should just be the autoextracted. Once they are fixed, then there should be a file in processed/ instead.

**Comment by Daniel-Ind** [comment]
- Does that mean I should then move the manually extracted and, automatically extracted then fixed files to the processed when pushing?
- I also had another question, I wanted to know if it is fine if each sentence in the processed file should be on its own line or if the current format is fine going forward?

**Comment by vukosim** [comment]
One the first one, yes. Please move them to processed when pushing. 

on the second one yes, don't worry about the per sentence anymore. @Daniel-Ind

**Comment by vukosim** [comment]
LGTM @Daniel-Ind

**Pull request merged**
