### PR TITLE
New stories

### PR DESCRIPTION
**Pull request by vukosim**

### CODE REVIEW

**Review by vukosim — COMMENTED** [review]
Can you add a reame to the src folder

All readmes should be 

README.md

@Daniel-Ind

**Comment by vukosim** [comment]
Also please update the DataStatement

**Comment by Daniel-Ind** [comment]
> Can you add a reame to the src folder
> 
> All readmes should be
> 
> README.md
> 
> @Daniel-Ind

- I have added the README file to the src folder
- I have changed all the README files to README.md

**Comment by Daniel-Ind** [comment]
> Also please update the DataStatement

@vukosim 
- If its not an issue, I will go over the DataStatement file over the weekend as there are quite a number of sections.
- I will note the questions I am unable to answer and wait for your feedback.

**Pull request merged**
