### PR TITLE
Add latest paper in all languages

### PR DESCRIPTION
**Pull request by Daniel-Ind**

### CODE REVIEW

**Comment by vukosim** [comment]
Can we maybe do this. Create folders for each edition amd then put the pdfs there?

raw/2022-07-ed1/

**Comment by Daniel-Ind** [comment]
> Can we maybe do this. Create folders for each edition amd then put the pdfs there?
> 
> raw/2022-07-ed1/

- Folder for latest edition has been created and files have been renamed and added to the folder.
- Further folders on past editions with accompanying files will follow.

**Review by vukosim — COMMENTED** [review]
LGTM

**Comment by Daniel-Ind** [comment]
- First set of papers have been uploaded using all-Papers branch
- Papers from year 2022 to 2020.
- Folders have been created accordingly and more will follow

**Pull request merged**
